[application]
name = "taskmod-frontend"
default_platform = "web"

[web.app]
title = "TaskMod - AI Agent 工作台"

[web.watcher]
watch_path = ["src", "assets"]
reload_html = true

[web.resource]
style = ["tailwind.css"]

[web.resource.dev]
style = []
script = []
